apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}-config
data:
    SPRING_DATASOURCE_URL: jdbc:postgresql://172.31.0.6:5432/organization_project_user
    SPRING_DATASOURCE_USERNAME: postgres