apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "microservice.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
