apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    app: {{ include "microservice.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "microservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "microservice.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name:  ORG_SERVICE_URL_ORGANIZATION_PROJECT_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "microservice.fullname" . }}-config
                  key:  ORG_SERVICE_URL_ORGANIZATION_PROJECT_USER

            - name: ORG_SERVICE_URL_BOARD_TASK
              valueFrom:
                configMapKeyRef:
                  name: {{ include "microservice.fullname" . }}-config
                  key: ORG_SERVICE_URL_BOARD_TASK