apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authorization-user-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: repo=europe-north1-docker.pkg.dev/problem-based-learning-462218/authorization-user-api/authorization-user-api
    argocd-image-updater.argoproj.io/repo.update-strategy: newest-build
    argocd-image-updater.argoproj.io/repo.write-back-method: git
spec:
  project: microservices
  source:
    repoURL: "https://github.com/scripa01/pbl-project-devops"
    targetRevision: main
    path: charts/authorization-user-api
  destination:
    server: https://kubernetes.default.svc
    namespace: apis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
