apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: organization-project-user-api
  namespace: argocd
spec:
  project: microservices
  source:
    repoURL: "https://github.com/scripa01/pbl-project-devops"
    targetRevision: HEAD
    path: charts/organization-project-user-api
  destination:
    server: https://kubernetes.default.svc
    namespace: apis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
