apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}-config
data:
    SPRING_DATASOURCE_URL: jdbc:postgresql://172.31.0.5:5432/board-task
    SPRING_DATASOURCE_USERNAME: postgres